services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile

    command:
      - "gunicorn"
      - "mysite.wsgi:application"
      - "--bind"
      - "0.0.0.0:8080"
    ports:
      - "8000:8080"
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    volumes:
      - ./mysite/database:/app/database
      - ./staticfiles:/app/staticfiles
    environment:
      - DJANGO_ALLOWED_HOSTS=103.74.95.89
      - DJANGO_DEBUG=1



