# Generated by Django 5.1.3 on 2024-12-17 18:58

import django.db.models.deletion
import shopapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0011_productimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-name"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time when order was created",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(
                blank=True,
                help_text="Enter the delivery address",
                verbose_name="Delivery Address",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                help_text="Products included in the order",
                related_name="orders",
                to="shopapp.product",
                verbose_name="Products",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="promocode",
            field=models.CharField(
                blank=True,
                help_text="Enter promotional code if available",
                max_length=20,
                verbose_name="Promo Code",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="receipt",
            field=models.FileField(
                help_text="Order receipt document",
                null=True,
                upload_to="orders/receipts/",
                verbose_name="Receipt",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                help_text="Customer who placed the order",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="archived",
            field=models.BooleanField(
                default=False, help_text="Is product archived?", verbose_name="Archived"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, help_text="Product description", verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.SmallIntegerField(
                default=0, help_text="Discount percentage", verbose_name="Discount"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Enter product name", max_length=100, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Product preview image",
                null=True,
                upload_to=shopapp.models.product_preview_directory_path,
                verbose_name="Preview image",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Product price in USD",
                max_digits=8,
                verbose_name="Price",
            ),
        ),
    ]
