# Generated by Django 5.1.3 on 2024-12-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0012_alter_order_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True,
                db_index=True,
                help_text="Product description",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Enter product name",
                max_length=100,
                verbose_name="Name",
            ),
        ),
    ]
